### ISSUE TITLE
Commodore OS Virus Found

### ISSUE THREAD

**Issue by vagnerafonso** [SparrOSDeveloperTeam/COS#1]
Greetings Team,

I went to download the Commodore OS Vision 2 from your Google Drive https://drive.google.com/folderview?id=19VI1oqTvPSEMcy27bi6AlQKz5EP67WuC and received an error the there was a virus detected in one of the zip files. (see attachment) . 
![cos virus](https://user-images.githubusercontent.com/40894056/42384088-0fec7be8-8107-11e8-980b-ea4f573a5f27.png) .  I just wanted to bring it to your attention. 

Regards,

Vagner Afonso

**Comment by SparrOSDeveloperTeam** [comment]
Vagner, I can assure you there is no virus. Seeing as though Google Drive will not allow you to download Commodore OS Vision II, I will add the archives to Github Releases. The archive was created with WinRAR which is a trusted software by most forums and people. The archives should all be uploaded to Github by tomorrow so be sure to check back then.

Thanks for pointing this out.

- SparrOSDeveloperTeam

**Comment by vagnerafonso** [comment]
Greetings Team, 

Thanks for this information. I check back tomorrow for the uploads. Much appreciated.

Thanks,

Vagner Afonso

**Comment by SparrOSDeveloperTeam** [comment]
Hi again,

Our internet upload quality started declining today so we will be uploading to DropBox tomorrow. Estimated time of upload is between 4P-5P (EST) tomorrow. Sorry about that.

SparrOSDeveloperTeam

**Comment by vagnerafonso** [comment]
Greeting Team,

Not a problem. Keep me
posted as soon as you’ve uploaded the archives.

Thanks,

Vagner Afonso

**Comment by SparrOSDeveloperTeam** [comment]
The Commodore OS Visions II files are being uploaded to Dropbox right now. [This link](https://www.dropbox.com/sh/arljpzkg2g235pj/AAApUHK7eyOSiSZIOTYXPWwla?dl=0) will take you to the folder where all the archives will be uploaded to. If you run into any other problems when installing Commodore OS Vision II let us know.

SparrOSDeveloperTeam

**Comment by SparrOSDeveloperTeam** [comment]
@vagnerafonso The files are all uploaded to [Dropbox](https://www.dropbox.com/sh/arljpzkg2g235pj/AAApUHK7eyOSiSZIOTYXPWwla?dl=0). If you run into any more problems please let us know.

**Comment by vagnerafonso** [comment]
Greetings Team,

I've successfully downloaded the files. 

Thanks.
